accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name="logout"),
]

workout/urls.py
from django.urls import path
from . import views

app_name = 'workout'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreateWorkoutView.as_view(), name='post'),
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    path('user_list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='workout_detail'),
    path('comment/create/<int:pk>/', views.Comment.as_view(), name='comment'),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('workout/<int:pk>/delete/', views.WorkoutDeleteView.as_view(), name='delete'),
    path('workout/<int:pk>/update/', views.WorkoutUpdateView.as_view(), name='update'),
    path('data/', views.data_screen, name='data'),
    path('data/plot', views.get_place_svg, name='img_plot'),
]

workoutProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workout.urls')),
    path('', include('accounts.urls')),
    # パスワードリセット申込ページ
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    # メール送信完了ページ
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    # パスワードリセットページ
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    # パスワードリセット完了ページ
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

workout/models.py
from pyexpat import model
from django.db import models
from accounts.models import CustomUser
from django.utils import timezone

class Place(models.Model):
    title = models.CharField(
        verbose_name ='カテゴリ1',
        max_length = 20,
    )

    def __str__(self):
        return self.title

class Category(models.Model):
    title = models.CharField(
        verbose_name ='カテゴリ2',
        max_length = 20,
    )

    def __str__(self):
        return self.title



class WorkoutPost(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name = 'ユーザー',
        on_delete = models.CASCADE,
    )

    place = models.ForeignKey(
        Place,
        verbose_name = 'カテゴリ1',
        on_delete = models.PROTECT,
    )

    category = models.ForeignKey(
        Category,
        verbose_name = 'カテゴリ2',
        on_delete = models.PROTECT
    )
    
    title = models.CharField(
        verbose_name = 'タイトル',
        max_length = 200,
    )

    content = models.TextField(
        verbose_name = '本文',
    )

    image1 = models.ImageField(
        verbose_name = 'イメージ１',
        upload_to = 'photos',
    )

    posted_at = models.DateTimeField(
        verbose_name = '投稿日時',
        auto_now_add = True,
    )

    updated_at = models.DateTimeField(
        verbose_name = '更新日時',
        auto_now_add = True,
    )

class Comment(models.Model):
    target = models.ForeignKey(WorkoutPost, on_delete=models.CASCADE, verbose_name='対象記事')
    text = models.TextField('本文')

workout/forms.py
from dataclasses import field
from django.forms import ModelForm, Textarea
from .models import WorkoutPost, Comment

class WorkoutPostForm(ModelForm):
    class Meta:
        model = WorkoutPost
        fields = ['title', 'category', 'place', 'content', 'image1']
        widgets = {
            'content': Textarea(attrs={'cols':30}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

workout/views.py
from dataclasses import field
from multiprocessing import context
from re import template
from turtle import right
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, ListView, DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.utils import timezone
from matplotlib.collections import PathCollection
from numpy import place

import workout
from .forms import WorkoutPostForm, CommentForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import WorkoutPost, Comment
from django.http import Http404, HttpResponse
from django.http.response import JsonResponse
import io
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import base64

class IndexView(ListView):
    template_name = 'index.html'
    queryset = WorkoutPost.objects.order_by('-posted_at')
    paginate_by = 4

#デコレーターによりCreateViewへのアクセスはログインユーザーに限定される。
@method_decorator(login_required, name='dispatch')
class CreateWorkoutView(CreateView):
    form_class = WorkoutPostForm
    template_name = 'post.html'
    success_url = reverse_lazy('workout:post_done')

    def form_valid(self, form):
        #フォームのバリデーションを通過したときに呼ばれる.
        #フォームデータの登録をここで行ってる！
        postdata = form.save(commit=False)
        postdata.user = self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name = 'post_done.html'

class UserView(ListView):
    template_name = 'index.html'
    paginate_by = 4

    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = WorkoutPost.objects.filter(user=user_id).order_by('-posted_at')
        return user_list


class DetailView(DetailView):
    template_name = 'detail.html'
    model = WorkoutPost

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # テンプレートにコメント作成フォームを渡す
        context['comment_form'] = CommentForm

        return context

class Comment(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        pk = self.kwargs.get('pk')
        post = get_object_or_404(WorkoutPost, pk=pk)
        #post = WorkoutPost.objects.get(id=pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        #return super().form_valid(form)
        return redirect('workout:workout_detail', pk=pk)

    


class MypageView(ListView):
    template_name = 'mypage.html'
    paginate_by = 4

    def get_queryset(self):
        queryset = WorkoutPost.objects.filter(user=self.request.user).order_by('-posted_at')
        return queryset

    
class WorkoutDeleteView(DeleteView):
    model = WorkoutPost
    template_name = 'delete.html'
    success_url = reverse_lazy('workout:mypage')

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class WorkoutUpdateView(UpdateView):
    model = WorkoutPost
    template_name = 'edit.html'
    fields = ('title', 'category', 'place', 'content', 'image1')
    success_url = reverse_lazy('workout:index')

    def form_valid(self, form):
        postdata = form.save(commit=False)
        postdata.updated_at = timezone.now()
        postdata.save()
        return super().form_valid(form)


def get_place_svg(request):

    def make_chart(x, y):
        plt.bar(x, y, color='#00d5ff')
        plt.xlabel('Place')
        plt.ylabel('Amounts')
    
    def convert_to_svg():
        buffer = io.BytesIO()
        plt.savefig(buffer, format='svg', bbox_inches='tight')
        s = buffer.getvalue()
        buffer.close()
        return s

    A = 0
    G = 0
    J = 0
    O = 0
    for postdata in WorkoutPost.objects.all():
        if postdata.place_id == 1:
            A += 1;
        if postdata.place_id == 2:
            G += 1;
        if postdata.place_id == 3:
            J += 1;
        if postdata.place_id == 4:
            O += 1;

    x = ['Anytime Fitness', 'Gold Gym', 'Joy Fit', 'Other']
    y = [A, G, J, O]

    make_chart(x, y)

    svg = convert_to_svg()
    plt.cla()
    
    return HttpResponse(svg, content_type='image/svg+xml')

def data_screen(request):
    return render(request, 'data.html')


workout/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>{% block title %}{% endblock title %}</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
        <link href="{% static 'css/my-style.css' %}" rel="stylesheet" />
        <link rel="icon" type="image/png" href="{% static '/assets/favicon2.png' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css2?family=Lobster" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    </head>
    
    <body> 
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light my-nav" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'workout:index' %}">Workout SNS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'workout:mypage' %}">マイページ</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'workout:data' %}">データ</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:logout' %}">ログアウト</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'password_reset' %}">パスワードのリセット</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:signup' %}">サインアップ</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:login' %}">ログイン</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'workout:data' %}">データ</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Page Header-->
        {% block header %}{% endblock header %}

        <div class="scroll-top">
            <a href="#">↑</a>
        </div>

        <!-- Main Content-->
        {% block contents %}{% endblock contents %}

        <!-- Footer-->
        <footer class="border-top">
            <a href="{% url 'workout:index' %}" class="btn btn--cubic btn--shadow btn-back" style="padding:10px; margin-left:5%;">Back to top</a>
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.facebook.com">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.co.jp">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Ryoto Taga 2021</div>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/script.js' %}"></script>
    </body>
</html>

workout/templates/data.html
{% extends 'base.html' %}

{% load static %}

{% block title %}data{% endblock title %}

    {% block header %}
    <header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h2>利用されているジム</h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock header %}

    {% block contents %}
    <div class="data-image">
        <img src="{% url 'workout:img_plot' %}">
    </div>
    {% endblock contents %}

workout/templates/delete.html
<form method="POST">
<br>
<p>削除してもよろしいですか？</p>
{% csrf_token %}
<button type="submit">
削除
</button>
<a href="{% url 'workout:detail' object.pk %}" class="btn btn-secondary my-2">キャンセル</a>

workout/templates/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Detail{% endblock title %}

    {% block header %}
    <header class="masthead" style="background-image: url({% static 'assets/crossfit.jpg' %})">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1>{{ object.title }}</h1>
                        <p class="meta detail-info">{{ object.posted_at }}に投稿</p>
                        <p class="meta detail-info">内容：{{ object.category}}</p>
                        <p class="meta detail-info">場所：{{ object.place }}</p>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock header %}

    {% block contents %}
    <article>
        <div class="detail-container container" style="width : 100%">
            <div class="row detail-row detail-left">
                <img src="{{ object.image1.url }}" style="width : 100%; height : 100%">
            </div>
            <div class="detail-right detail-row">
                <div class="row">
                    <p class="detail-content">{{ object.content|linebreaksbr }}</p>
                </div>
                <div class="row button-row">
                    <p><a onclick="api_like()"><span id="like">3</span>Good</a></p>
                </div>
                <div class="detail-button">
                    <a href="{% url 'workout:update' object.pk %}" class="btn btn--cubic btn--shadow">Edit</a>
                    <a href="{% url 'workout:index' %}" class="btn btn--cubic btn--shadow">Back</a>
                    {% if request.user == object.user %}
                    <form method="POST"><a href="{% url 'workout:delete' object.pk %}" class="btn btn--cubic btn--shadow">Delete</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </article>


    <div class="comment">

        <div class="comment">
            <h2>コメント一覧</h2>
            {% for comment in workoutpost.comment_set.all %}
            <div class="comment-text">
              <p>{{ comment.text }}</p>
            </div>
            {% endfor %}
        </div>

        <div class="comment-form">
        <h2>コメント投稿</h2>
        <!-- コメント作成用のURLを渡す -->
        <form action="{% url 'workout:comment' workoutpost.pk %}" method="post">
            {% csrf_token %}
            {{ comment_form}}
            <div>
            <button type="submit">送信</button>
            </div>
        </form>

    </div>
{% endblock contents %}

{% block extrahead %}
<style media="screen">
  .title {
    font-size: 2rem;
  }

  .text {
    margin-top: 30px;
  }

  .comment {
    margin-top: 30px;
  }

  .comment-text {
    margin-top: 20px;
  }

  label {
    display: block;
  }
</style>
{% endblock %}

workout/templates/edit.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Edit{% endblock title %}

    {% block header %}
    <header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1>{{ object.title }}の編集</h1>
                        <span class="meta">
                        {{ object.posted_at }}に投稿
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock header %}



    {% block contents %}
    <form method="post">{% csrf_token %}
        <table>
            <tr>
                <th>タイトル：</th>
                <td>{{ form.title }}</td>
            </tr>
            <tr>
                <th>内容：</th>
                <td>{{ form.category }}</td>
            </tr>
            <tr>
                <th>場所：</th>
                <td>{{ form.place }}</td>
            </tr>
            <tr>
                <th>本文：</th>
                <td>{{ form.content }}</td>
            </tr>
            <tr>
                <th>画像：</th>
                <td>{{ form.image1 }}</td>
            </tr>
        </table>
        <input type="submit" value="Edit">
    </form>
    <a href="{% url 'workout:workout_detail' object.pk %}">Back</a>
    {% endblock contents %}

workout/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Workout SNS{% endblock title %}

        <!-- ナビゲーションはbase.html -->

        <!-- Page Header-->
        {% block header %}
        <header class="masthead header-img" style="background-image: url({% static 'assets/crossfit.jpg' %}); background-size: cover; background-position: center; width: 100%; height: 100vh;">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center" id="my-top-container">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading my-heading">
                            <h1 font style="font-family: 'Lobster',sans-serif;">Hangout of Trainee</h1>
                            <span class="subheading">トレーニングに関することを話し合える場です</span>
                        </div>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="menu">
                            <a href="{% url 'workout:post' %}" class="btn btn--cubic btn--shadow">Post</a>
                            <a href="{% url 'accounts:logout' %}" class="btn btn--cubic btn--shadow">Log out</a>
                        </div>
                    {% else %}
                        <div class="menu">
                            <a href="{% url 'accounts:signup' %}" class="btn btn--cubic btn--shadow">Sign up</a>
                            <a href="{% url 'accounts:login' %}" class="btn btn--cubic btn--shadow">Log in</a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </header>
        {% endblock header %}

        <!-- Main Content-->
        {% block contents %}
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    {% for record in object_list %}
                    <!-- Post preview-->
                    <div class="post-container post-preview">
                        <div class="index-right">
                            <a href="{% url 'workout:workout_detail' record.pk %}">
                                <h2>{{ record.title }}</h2>
                                <h3><span style="font-size : 16px">{{ record.content|truncatechars:30 }}</span></h3>
                                <div>
                                    <img src="{{ record.image1.url }}" style="width : 100%; height : 100%">
                                </div>
                            </a>
                        </div>
                        <div class="index-left">
                            <p>
                                Posted by
                                {% if request.user.id == record.user.id %}
                                    <a href="{% url 'workout:mypage'%}">{{ record.user.username }}(your)</a>
                                {% else %}
                                    <a href="{% url 'workout:user_list' user=record.user.id %}">{{ record.user.username }}</a>／
                                {% endif %}
                                {{ record.posted_at }}に投稿／
                                内容：
                                {{ record.category}}／場所：
                                {{ record.place }}／
                                いいね
                            </p>
                        </div>
                    </div>

                    <!-- Divider-->
                    <hr class="my-4" />
                    {% endfor %}
                    {% include "pagination.html" %}
                </div>
            </div>
        </div>
        {% endblock contents %}

workout/templates/mypage.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Mypage{% endblock title %}

    {% block header %}
    <header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        {% if user.is_authenticated %}
                            <div style="text-align:center">
                                <h2>{{ user.username }}さんのマイページ</h2>
                                {% if object_list.count == 0 %}
                                    <p>{{ user.username }}さんの投稿はありません</p>
                                {% else %}
                                    <p>投稿<strong>{{ object_list.count }}</strong>件</p>
                                {% endif %}
                                <a href="{% url 'workout:post' %}" class="sign">投稿する</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock header %}

    <!-- Main Content-->
    {% block contents %}
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {% for record in object_list %}
                    <!-- Post preview-->
                    <div class="post-container post-preview">

                        <div class="index-right">
                            <a href="{% url 'workout:workout_detail' record.pk %}">
                                <h2>{{ record.title }}</h2>
                                <h3><span style="font-size : 16px">{{ record.content|truncatechars:30 }}</span></h3>
                                <div class="post-image">
                                    <img src="{{ record.image1.url }}" style="width : 100%; height : 100%">
                                </div>
                            </a>
                        </div>

                        <div class="index-left">
                            <p>
                                Posted by
                                {% if request.user.id == record.user.id %}
                                    <a href="{% url 'workout:mypage'%}">{{ record.user.username }}(your)</a>
                                {% else %}
                                    <a href="{% url 'workout:user_list' user=record.user.id %}">{{ record.user.username }}</a>／
                                {% endif %}
                                {{ record.posted_at }}に投稿／
                                内容：
                                {{ record.category}}／場所：
                                {{ record.place }}／
                                いいね
                            </p>
                        </div>

                    </div>
                <!-- Divider-->
                <hr class="my-4" />
                {% endfor %}
                {% include "pagination.html" %}
            </div>
        </div>
    </div>
    {% endblock contents %}
    

workout/templates/pagination.html
{% if is_paginated %}
    <!-- 左右の中央に配置 -->
    <ul class="pagination" style="justify-content: center">
        <!-- 前のページがある場合 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link"
                    href="?page={{ page_obj.previous_page_number }}"
                    aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        <!-- ページ数の表示 -->
        {% for num in paginator.page_range %}
            <!-- ページ番号が存在しない場合 -->
            {% if page_obj.number == num %}
                <li class="page-item active">
                    <sapn class="page-link">{{ num }}</span>
                </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{num}}">{{ num }}</a>
            </li>
            {% endif %}
        {% endfor %}
        <!-- 次ページへのリンク -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link"
                    href="?page={{ page_obj.next_page_number }}"
                    aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
{% endif %}

workout/templates/post.html
{% extends 'base.html' %}

{% block title %}Post{% endblock title %}

    {% block contents %}
    <br><br>
    <div>
        <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>
            <li class="list-content">
                <p class="list-title">タイトル</p>
                <p class="form">{{ form.title }}</p>
            </li>
            <li class="list-content">
                <p class="list-title">内容</p>
                <p class="form">{{ form.category }}</p>
            </li>
            <li class="list-content">
                <p class="list-title">場所</p>
                <p class="form">{{ form.place }}</p>
            </li>
            <li class="list-content">
                <p class="list-title">本文</p>
                <p class="form">{{ form.content }}</p>
            </li>
            <li class="list-content">
                <p class="list-title">画像</p>
                <p class="form">{{ form.image1 }}</p>
            </li>
        </ul>
        <button type="submit">投稿する</button>
    </div>
    {% endblock contents %}

workout/templates/post_done.html
{% extends 'base.html' %}

{% block title %}Post Done{% endblock title %}

    {% block contents  %}
    <br><br>
    <div>
        <h4>投稿が完了しました。</h4>
    </div>
    {% endblock contents %}