accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name="logout"),
]

workout/urls.py
from django.urls import path
from . import views

app_name = 'workout'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('post/', views.CreateWorkoutView.as_view(), name='post'),
    path('post_done/', views.PostSuccessView.as_view(), name='post_done'),
    path('user_list/<int:user>', views.UserView.as_view(), name='user_list'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='workout_detail'),
    path('comment/create/<int:pk>/', views.Comment.as_view(), name='comment'),
    path('mypage/', views.MypageView.as_view(), name='mypage'),
    path('workout/<int:pk>/delete/', views.WorkoutDeleteView.as_view(), name='delete'),
    path('workout/<int:pk>/update/', views.WorkoutUpdateView.as_view(), name='update'),
    path('data/', views.data_screen, name='data'),
    path('data/plot', views.get_place_svg, name='img_plot'),
]

workoutProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workout.urls')),
    path('', include('accounts.urls')),
    # パスワードリセット申込ページ
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    # メール送信完了ページ
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    # パスワードリセットページ
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_form.html'), name='password_reset_confirm'),
    # パスワードリセット完了ページ
    path('reset/done', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_done.html'), name='password_reset_complete'),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "signup.html"
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        # formオブジェクトのフィールドの値をデータベースに保存
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name = "signup_success.html"

accounts/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log in</title>
    <link href="{% static 'css/login.css' %}" rel="stylesheet" />
</head>
<body>
    <div>
        {% if form.errors %}
            <p style="color:red">ユーザー名とパスワードが一致しません。</p>
        {% endif %}
    </div>

    <!-- ログインのフォームを配置 -->
    <form method="POST">
        {% csrf_token %}
        <h1>ログイン</h1>
        <label for="Username">User name</label>
        <input type="text" name="username" id="id_username" maxlength="150" autocapitalize="none" autocomplete="username" placeholder="ユーザー名" required autofocus>
        <label for="password">Password</label>
        <input type="password" name="password" id="id_password" autocapitalize="none" autocomplete="password" placeholder="パスワード" required>

        <input type="submit" value="ログイン">

        <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a></p>

        <!-- ログイン直後のリダイレクト先 -->
        <input type="hidden" name="next" value="{% url 'workout:index' %}">
    </form>

</body>
</html>

accounts/templates/logout.html
{% extends 'base.html' %}

{% block title %}Log out{% endblock title %}

    {% block contents %}
    <h3>ログアウトしました。</h3>
    <p><a href="{% url 'workout:index' %}">トップページへ</a></p>
    {% endblock contents %}

accounts/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock title %}

    {% block contents %}
    <h3>パスワードリセットをしますか？</h3>
    <p>登録済みのメールアドレスを入力してください。
        パスワードリセットのリンクを送信します
    </p>
    <br>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="メールを受け取る" /><br>
    </form>
    <br>
    <a href="{% url 'workout:index' %}">トップページへ</a>
    {% endblock contents %}

accounts/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <style>
            .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
            }
        </style>
    </head>
    <body>
        <div>
            <h2>パスワードリセットが完了しました</h2>
            <br>
            <a href="{% url 'workout:index' %}">トップページへ</a>
        </div>
    </body>
</html>

accounts/templates/password_reset_form.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <style>
            .pad{
            background-color: lavender;
            border: solid 2px;
            padding-top: 30px;
            padding-bottom: 50px;
            padding-left: 100px;
            margin-top: 50px;
            margin-right: 70px;
            margin-left: 70px;
            }
        </style>
    </head>
    <body>
        <div>
            <h2>Workout</h2>
            <h4> 新しいパスワードを2回入力してください。これにより、
                正しく入力できたことが確認されます。
            </h4>

            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="パスワードリセット">
            </form>
        </div>
    </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}

{% block title %}Send password rest mail{% endblock title %}

    {% block contents %}
    <h5>パスワードのリセット手順をメールで送信しました。</h6>
    <h6>メールが届かない場合は、メールアドレスを確認し、迷惑メールも確認してください。</h6>
    <a href="{% url 'workout:index' %}">トップページへ</a>
    {% endblock contents %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block title %}Sign up{% endblock title %}

    {% block contents %}
    <hr>
    <div class="container">
        <div class="row">
            <div class="col offset-2">
                <h3>サインアップ</h3>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <p>
                            {{ field.label_tag }}<br>
                            {{ field }}
                            {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </p>
                    {% endfor %}
                    <p style="color: red;">#メールアドレスはパスワードをリセットする際に必要になりますので、登録しておくことをお勧めします。</p>
                    <input type="submit" value="Sign up">
                </form>
                <br>
                <p><a href="{% url 'workout:index' %}">登録をやめてトップページに戻る</a></p>
            </div>
        </div>
    </div>
    
    {% endblock contents %}

accounts/templates/signup_success.html
{% extends 'base.html' %}

{% block title %}Registration Success{% endblock title %}

    {% block contents %}
    <h3>登録が完了しました。</h3>
    <p><a href="{% url 'accounts:login' %}">ログインはこちら</a></p>
    {% endblock contents %}